개념/Django/class/02-template-urls/articles/urls.py
from django.urls import path

# 명시적 상대경로
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('dinner/', views.dinner, name='dinner'),
    path('search/', views.search, name='search'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('<int:num>/', views.detail),
    path('hello/<str:name>/', views.greeting, name='greeting'),
]

개념/Django/class/02-template-urls/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

'''
from django.contrib import admin
from django.urls import path
from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('index/', views.index),
    path('dinner/', views.dinner),
    path('search/', views.search),
    path('throw/', views.throw),
    path('catch/', views.catch),
    path('hello/<str:name>/',views.greeting),
]
'''

개념/Django/class/02-template-urls/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

개념/Django/class/02-template-urls/articles/models.py
from django.db import models

# Create your models here.

개념/Django/class/02-template-urls/pages/models.py
from django.db import models

# Create your models here.

개념/Django/class/02-template-urls/articles/views.py
import random
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {
        'name' : 'alice',
        'ssafy' : {
            'key' : 'value'
        }
    }
    return render(request, 'articles/index.html', context)



def dinner(request):
    foods = [
        '국밥',
        '국수',
        '카레',
        '탕수육',
    ]
    picked = random.choice(foods)
    context = {
        'foods': foods,
        'picked': picked,
    }
    return render(request, 'articles/dinner.html', context)


def search(request):
    return render(request, 'articles/search.html')


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # 사용자가 요청보낸 데이터를 추출해서 context 딕셔너리에 세팅
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def detail(request, num):
    context = {
        'num': num,
    }
    return render(request, 'articles/detail.html', context)


def greeting(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/greeting.html', context)

개념/Django/class/02-template-urls/pages/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

개념/Django/class/02-template-urls/articles/templates/articles/catch.html
{% extends "base.html" %}

{% block content %}
  <h1>Catch</h1>
  <p>당신이 입력한 데이터는 {{ message }}입니다.</p>
{% endblock content %}

개념/Django/class/02-template-urls/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Detail</h1>
  <h3>{{ num }}번 글 입니다.</h3>
{% endblock content %}

개념/Django/class/02-template-urls/articles/templates/articles/dinner.html
{% extends "base.html" %}

{% block content %}
  <h1>dinner</h1>
  <p>{{ picked }} 메뉴는 {{ picked|length }}글자 입니다.</p>
  {% comment %} <p>{{foods}}</p> #['국밥', '국수', '카레', '탕수육'] 이렇게 출력됨  {% endcomment %} 

  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {% comment %} {% if  %}{% endif %} {% endcomment %}
  {% comment %} {% if  %} 주석 {% endif %} {% endcomment %}

  {% if foods|length == 0 %}
    <p>메뉴가 소진 되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
{% endblock content %}

개념/Django/class/02-template-urls/articles/templates/articles/greeting.html
{% extends "base.html" %}

{% block content %}
  <h1>Greeting</h1>
  <p>{{ name }}님 안녕하세요!</p>
{% endblock content %}

개념/Django/class/02-template-urls/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
  <h1>안녕하세요! {{ name }}</h1>
  <a href="{% url "articles:dinner" %}">dinner</a>
  <a href="{% url "articles:search" %}">search</a>
  <a href="{% url "articles:throw" %}">throw</a>
  <a href="{% url "pages:index" %}">두번째 앱의 인덱스</a>
{% endblock content %}

개념/Django/class/02-template-urls/articles/templates/articles/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Fake Naver</h1>
  <form action="https://search.naver.com/search.naver" method="GET">
      {% comment %}  로그인 할 때는 method="POST"를 사용(나중에씀~) {% endcomment %}

    <input type="text" name="query">
    <input type="submit">
  </form>
{% endblock content %}

개념/Django/class/02-template-urls/articles/templates/articles/throw.html
{% extends "base.html" %}

{% block content %}
  <h1>Throw</h1>
  {% comment %} <form action="http://127.0.0.1:8000/catch/" method="GET"> {% endcomment %}
  {% comment %} <form action="/articles/catch/" method="GET"> {% endcomment %}
  <form action="{% url "articles:catch" %}" method="GET">
    <input type="text" name="message">
    <input type="submit">
  </form>
{% endblock content %}

개념/Django/class/02-template-urls/pages/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
  <h1>두번째 앱의 인덱스</h1>
{% endblock content %}