개념/Django/class/05-orm-with-view/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name = 'detail'),
    path('new/', views.new, name = 'new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    # <int:pk>/update/ 작성 순서는 상관 없음
    
]

개념/Django/class/05-orm-with-view/articles/views.py
from django.shortcuts import render, redirect
# 모델 클래스 가져오기
from .models import Article

# Create your views here.
def index(request):
    # 게시글 전체 조회 요청 to DB
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def detail(request, pk) :
    # url로부터 전달 받은 pk를 활용해 데이터를 조회
    article = Article.objects.get(pk=pk)    # id = pk(입력값)
    context = {
        'article' : article,

    }

    return render(request, 'articles/detail.html', context)

def new(request) :
    # 게시글 작성 페이지 응답
    return render(request,'articles/new.html')

def create(request) :
    # 1. 사용자 요청으로부터 입력 데이터를 추출
    title = request.POST.get('title')
    content = request.POST.get('content')

    
    # 2. 추출한 입력 데이터를 활용해 DB에 저장 요청 : save

    # # 저장1 : 
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 저장2 (1번보다 간단해서 더 선호함)
    article = Article(title = title, content = content)
    article.save()

    # # 저장3 : 유효성 검사(save 전에 해야함)를 하기 어려움
    # Article.objects.create(title = title, content = content)

    return redirect('articles:detail', article.pk)


def delete(request,pk) :
    # 어떤 게시글 삭제할지 조회
    article = Article.objects.get(pk=pk)

    # 조회한 게시글 삭제
    article.delete()

    return redirect('articles:index')

def edit(request,pk) :
    # 어떤 게시글을 수정할 지 조회
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }

    return render(request, 'articles/edit.html.context')


def update(request,pk) :
    # 1. 어떤 게시글 수정할 지 조회
    article = Article.objects.get(pk=pk)

    # 2. 사용자로부터 받은 새로운 입력 데이터 추출
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 3. 기존 게시글의 데이터를 사용자로 받은 데이터로 할당
    article.title = title
    article.conent = content

    # 4. 저장
    article.save()

    return redirect('articles:detail', article.pk)

개념/Django/class/05-orm-with-view/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1> 작성이 완료되었습니다. </h1>
</body>
</html>

개념/Django/class/05-orm-with-view/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail</h1>
  <p>{{ article.pk }}번째 글</p>
  <hr>
  <p> 제목 : {{ article.title }}</p>
  <p> 내용 : {{ article.content }}</p>
  <p> 수정일 : {{ article.created_at }}</p>
  <p> 삭제일 : {{ article.updated_at }}</p>
  <hr>
  <form action="{% url "articles:delete" article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value ="삭제">
  </form>
  <a href="{% url "articles:index" %}">[back]</a>
  {% comment %} a태그는 POST 요청 불가 {% endcomment %}
  
</body>
</html>

개념/Django/class/05-orm-with-view/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Edit</h1>
  <form action={% url "artilces:update" article.pk %} method="POST">
    {% csrf_token %}
    <input type="text" name = "title" value = {{article.title}}>
    <textarea name="content" id="">{{article.content}}</textarea>
    {% comment %} textarea는 value가 없음 {% endcomment %}
    <input type="submit" value="수정">
  </form>
  
</body>
</html>

개념/Django/class/05-orm-with-view/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Articles</h1>
  <a href="{% url "articles:new" %}"></a>
  {% comment %} <p>{{ articles }}</p> {% endcomment %}
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url "articles:detail" article.pk %}">
      <p>글 제목: {{ article.title }}</p>
    </a>
    <p>글 내용: {{ article.content }}</p>
    <hr>
  {% endfor %}

</body>
</html>

개념/Django/class/05-orm-with-view/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>New</h1>
  <form action={% url "articles:create" %} method="POST">
    {% csrf_token %}
    <input type="text" name = "title">
    <textarea name="content" id=""></textarea>
    <input type="submit">
  </form>
  
</body>
</html>